CREATE TABLE [dbo].[EventAuth] (
    [EventAuthId]   UNIQUEIDENTIFIER NOT NULL,
	[EventId]		UNIQUEIDENTIFIER NOT NULL,
	[AuthId]		UNIQUEIDENTIFIER NOT NULL,
	[RoomId]		UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_EventAuth] PRIMARY KEY CLUSTERED ([EventAuthId] ASC)
);

