CREATE TABLE [dbo].[RoomName] (
    [RoomNameId]		UNIQUEIDENTIFIER NOT NULL,
    [EventId]			UNIQUEIDENTIFIER NOT NULL,
    [RoomId]			UNIQUEIDENTIFIER NOT NULL,
	[Name]				NVARCHAR(MAX)	 NOT NULL,
    CONSTRAINT [PK_RoomName] PRIMARY KEY CLUSTERED ([RoomNameId] ASC)
);

