CREATE TABLE [dbo].[Topic] (
    [TopicId]		UNIQUEIDENTIFIER NOT NULL,
    [EventId]		UNIQUEIDENTIFIER NOT NULL,
    [RoomId]		UNIQUEIDENTIFIER NOT NULL,
	[TopicText]		NVARCHAR(MAX)	 NOT NULL,
    CONSTRAINT [PK_Topic] PRIMARY KEY CLUSTERED ([TopicId] ASC)
);

